// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracker.Models;

namespace TimeTracker.Migrations
{
    [DbContext(typeof(TimeTrackerDbContext))]
    [Migration("20190930140342_InitialContext")]
    partial class InitialContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeTracker.Models.CostCenter", b =>
                {
                    b.Property<double>("TimePercentage");

                    b.Property<DateTime>("TotalTime");

                    b.Property<int>("UserId");

                    b.HasKey("TimePercentage");

                    b.ToTable("CostCenter");
                });

            modelBuilder.Entity("TimeTracker.Models.Profile", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("TimeTracker.Models.Time", b =>
                {
                    b.Property<DateTime>("Start");

                    b.Property<DateTime>("End");

                    b.Property<DateTime>("TotalTime");

                    b.Property<int>("UserId");

                    b.HasKey("Start");

                    b.ToTable("Time");
                });
#pragma warning restore 612, 618
        }
    }
}
